### ISSUE TITLE
The OBDH2 cannot communicate with the EPS2.

### ISSUE THREAD

**Issue by LucasAzulay** [spacelab-ufsc/obdh2#329]
The OBDH2 cannot communicate with the EPS2.

**Comment by joaoclaudioeb** [comment]
@LucasAzulay, we have been changing the EPS 2.0 code for the last couple of days, in some secondary branches, for testing, with names similar to _feature_device_XXX_, _feature_drivers_XXX_. These changes were merged into the _dev_firmware_. Then, this firmware was tested with EPS 2.0 and OBDH 2.0, both of which are plugged into our FlatSat. On the OBDH 2.0, it was used the code that is present in the _master_. With this setup, EPS 2.0 and OBDH 2.0 were able to communicate. The EPS recognizes the read requests (cmd = 1) and sends the data to the OBDH. The errors that occur on the OBDH side are related to TTC 2.0. Additionally, today we conducted some tests regarding the communication of TTC 2.0 with EPS 2.0. And, again, they were able to communicate. Soon we are going to merge these modifications into the _master_ for EPS, but for now, you can use the _dev_firmware_ of the EPS to see if you can achieve the same results as us. If you try this, let me know what your results are.

**Comment by LucasAzulay** [comment]
Thanks for the response, we implemented the EPS 2.0 code in the dev_firmware version and the communication between the OBDH 2.0 and EPS 2.0 worked as intended, the EPS recognized the read requests (cmd = 1), but we were not able to receive the data in the OBDH side (highlighted in the image).

**Comment by LucasAzulay** [comment]
Thanks for the response, we implemented the EPS 2.0 code in the dev_firmware version and the communication between the OBDH 2.0 and EPS 2.0 worked as intended, the EPS recognized the read requests (cmd = 1), but we were not able to receive the data in the OBDH side (highlighted in the image).
![Communication between the OBDH and EPS](https://user-images.githubusercontent.com/119054195/225704002-e7b66a21-75bf-45e6-ac6f-c0797a8f2034.jpeg)

**Comment by joaoclaudioeb** [comment]
@LucasAzulay, could you tell me if the TTC 2.0 was connected with OBDH 2.0 and EPS 2.0 during these tests that you conducted?

**Comment by LucasAzulay** [comment]
Yes, the three were connected.

**Comment by joaoclaudioeb** [comment]
Ok. Today I will make some small changes to the OBDH's firmware in the _dev_firmware_. I will then contact you again to ask you to do some testing.

**Comment by joaoclaudioeb** [comment]
@LucasAzulay, could you please use the code in _dev_firmware_ into the OBDH 2.0? You should see EPS 2.0 being able to receive multiple commands from OBDH 2.0. OBDH 2.0 should not show any EPS 2.0 related errors. Finally, you will still see TTC 2.0 related errors: 
![Captura de tela de 2023-03-17 19-23-17](https://user-images.githubusercontent.com/56377265/226063455-3420a5ff-6030-49bb-831f-0d403f9148c1.png)

**Comment by LucasAzulay** [comment]
We tested using the dev_firmware into the OBDH and we still have this erros.

![image](https://user-images.githubusercontent.com/119054195/227027037-bb9758e6-cf4d-451d-8513-7c6760b60c37.jpeg)

**Comment by joaoclaudioeb** [comment]
@LucasAzulay, could you please tell me if these errors occur recurrently? Here we have not yet observed these errors. And, please, could you share to us what are the modules' versions that you are using (e.g. EPS 2.0 **v0.1**)? We would like to know the version of the EPS, TTC and OBDH, if possible.

**Comment by LucasAzulay** [comment]
These errors still occurring. The OBDH is not receiving data from the EPS (image 2), and the EPS is receiving the commands correctly most of the time, but sometimes the commands are getting corrupted (image 4).
We are using the TTC 2.0 v0.4.2, OBDH 2.0 v10.0 and EPS v0.3.0.

![image](https://user-images.githubusercontent.com/119054195/228619914-e7175d64-0ffb-4a46-bbd2-4d014e2dd65c.jpeg)
![image](https://user-images.githubusercontent.com/119054195/228619956-99fc6f5c-247c-4bc4-b687-1b48e6c3776e.jpeg)
![image](https://user-images.githubusercontent.com/119054195/228620006-6d8273db-facc-4c01-af96-a9451d63316f.jpeg)
![image](https://user-images.githubusercontent.com/119054195/228620083-ae551656-7a7e-4749-8b77-0ce7c84b5f91.jpeg)

**Comment by joaoclaudioeb** [comment]
@LucasAzulay, sorry for the delayed response. We have not yet been able to replicate the errors, however, I have some observations:

1) Please check if in config/config.h the _CONFIG_SET_DUMMY_EPS_ is set to 0 or 1. I suggest trying to do the tests with this deactivated, that is, with 0.

2) I would like to ask you to do a little "test". Would it be possible to change the position of the OBDH in your FlatSat platform? You can put it in any other slot. 

Please report me if something changed during the tests. We will try to make more tests to replicate the errors.
